version: '3.9'
services: 
  api: 
    build: .
    ports: 
      - "3000:3000"
    depends_on:
      - mongo
      - redis

  redis:
    image: "redis:latest"

  mongo:
    image: mongo
    ports: 
      - "7000:27017"
    environment:
      MONGO_INITDB_DATABASE: chatapp
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example